import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | NorthStar Medic",
  description: "NorthStar Medic terms of service — governing use of our AI medical claim recovery platform.",
};

export default function TermsPage() {
  return (
    <main style={{ background: "var(--bg-dark)", color: "#fff", minHeight: "100vh" }}>
      <section style={{ maxWidth: "800px", margin: "0 auto", padding: "10rem 1.5rem 5rem" }}>
        <h1 style={{ fontSize: "2.5rem", fontWeight: "800", marginBottom: "1rem" }}>Terms of Service</h1>
        <p style={{ color: "var(--text-secondary)", marginBottom: "3rem" }}>Last updated: March 2026</p>

        <div style={{ color: "var(--text-secondary)", lineHeight: 1.8, fontSize: "0.95rem" }}>
          <Section title="1. Acceptance of Terms">
            By accessing or using NorthStar Medic (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These terms constitute a legally binding agreement between you and NorthStar Medic.
          </Section>

          <Section title="2. Description of Service">
            NorthStar Medic provides AI-powered medical claim denial analysis and appeal generation services. Our platform analyzes denied insurance claims, identifies recovery opportunities, and generates appeal letters for submission to insurance payers. The Service is designed for licensed healthcare providers, medical billing professionals, and authorized representatives.
          </Section>

          <Section title="3. Eligibility">
            You must be at least 18 years old and authorized to act on behalf of a healthcare provider or medical billing organization to use this Service. By creating an account, you represent that you have the authority to bind the organization you represent to these terms.
          </Section>

          <Section title="4. Account Registration">
            You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate, current, and complete information during registration. You are responsible for all activities that occur under your account.
          </Section>

          <Section title="5. HIPAA and Business Associate Agreement">
            Use of the Service for processing Protected Health Information (PHI) requires execution of a Business Associate Agreement (BAA). You must sign our BAA before uploading any PHI to the platform. You represent that you have the authority to disclose PHI to us for the purposes described in the BAA.
          </Section>

          <Section title="6. Service Fees and Payment">
            <strong>Guardian Pilot:</strong> $2,500 one-time fee plus 30% commission on recovered revenue.
            <br /><br />
            <strong>Growth Lattice:</strong> $7,500 setup fee plus 20% commission on recovered revenue.
            <br /><br />
            <strong>Network Core:</strong> Custom pricing for enterprise clients.
            <br /><br />
            All payments are processed through Stripe. Commission fees are calculated on the gross amount recovered and are invoiced upon confirmation of payer payment. You agree to pay all fees associated with your selected plan.
          </Section>

          <Section title="7. AI-Generated Content Disclaimer">
            Appeal letters and analysis reports generated by our AI are provided as tools to assist healthcare providers and billing professionals. <strong>AI-generated content does not constitute legal advice, medical advice, or a guarantee of claim recovery.</strong> You are responsible for reviewing all AI-generated content before submission to payers. NorthStar Medic is not a law firm and does not provide legal representation.
          </Section>

          <Section title="8. No Guarantee of Results">
            While our AI is designed to maximize recovery potential, we do not guarantee that any specific claim will be successfully recovered. Recovery rates depend on claim specifics, payer policies, clinical documentation, and other factors outside our control. Any projections or estimates presented on our website are hypothetical and based on industry benchmarks.
          </Section>

          <Section title="9. User Responsibilities">
            You agree to:
            <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
              <li>Provide accurate and complete claim data</li>
              <li>Review all AI-generated appeal letters before submission</li>
              <li>Comply with all applicable healthcare laws and regulations</li>
              <li>Not use the Service for fraudulent claims or billing</li>
              <li>Maintain appropriate authorization to submit claims on behalf of providers</li>
              <li>Not attempt to reverse-engineer, copy, or misuse our AI technology</li>
            </ul>
          </Section>

          <Section title="10. Intellectual Property">
            The Service, including its AI models, algorithms, user interface, and branding, is the property of NorthStar Medic and is protected by intellectual property laws. Appeal letters generated for your claims are licensed to you for use in claim recovery. You may not resell, redistribute, or commercialize the Service or its outputs without written permission.
          </Section>

          <Section title="11. Data Privacy">
            Your use of the Service is also governed by our <a href="/privacy" style={{ color: "var(--brand-primary)", textDecoration: "underline" }}>Privacy Policy</a>. By using the Service, you consent to the collection and use of information as described therein.
          </Section>

          <Section title="12. Limitation of Liability">
            To the maximum extent permitted by law, NorthStar Medic shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim arising from use of the Service shall not exceed the total fees you have paid to us in the twelve (12) months preceding the claim.
          </Section>

          <Section title="13. Indemnification">
            You agree to indemnify and hold harmless NorthStar Medic, its officers, directors, employees, and agents from any claims, losses, or damages arising from your use of the Service, your violation of these terms, or your submission of fraudulent or inaccurate claim data.
          </Section>

          <Section title="14. Termination">
            Either party may terminate this agreement at any time. Upon termination, you remain responsible for any outstanding commission fees on claims already recovered. We may suspend or terminate your access if you violate these terms or engage in fraudulent activity.
          </Section>

          <Section title="15. Modifications">
            We reserve the right to modify these Terms of Service at any time. We will notify registered users of material changes via email. Continued use of the Service after modifications constitutes acceptance of the updated terms.
          </Section>

          <Section title="16. Governing Law">
            These terms shall be governed by and construed in accordance with the laws of the United States and the state in which NorthStar Medic is incorporated, without regard to conflict of law principles.
          </Section>

          <Section title="17. Contact">
            For questions about these Terms of Service, contact us at:
            <br /><br />
            NorthStar Medic<br />
            Email: legal@northstarmedic.com
          </Section>
        </div>
      </section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "2.5rem" }}>
      <h2 style={{ fontSize: "1.25rem", fontWeight: "700", color: "var(--text-primary)", marginBottom: "0.75rem" }}>{title}</h2>
      <div>{children}</div>
    </div>
  );
}
